language:
  - c
  - bash
jobs:
  include:
    - os: osx
      osx_image: xcode12.5
install:
script:
  - ./tests/local-install-test.sh
  - ./tests/homebrew-test.sh
before_deploy:
  - ./utils/homebrew-package.sh
  - cd out/
deploy:
  provider: releases
  token: $GH_OAUTH_TOKEN
  file: homebrew-package.tar.gz
  name: "Brainfunc-$TRAVIS_TAG"
  body: "SHA256 hashsum of homebrew-package.tar.gz: $(cat homebrew-package.tar.gz.sha256sum)"
  cleanup: false
  on:
    tags: true
env:
  global:
    secure: NFnwO9O+kwYNc47fxtKNO4GEOZljqcvUfilSQV8NxUwn0RDuWCZqknhcXOJV03u8aqhUQqZGb9iK0iQtI13qwS3H41YpYpgpFlwWfP69CZUXJEOqOcqXF3FJlomeveNwtJTELOwJLgK5WppH9whrjrtvPe54WnSUbvX8etZioKuLg3riQLp0gY7PsqlXzLnqUIExBFBXJH41VtOl1p/efErQe2w/hfl3jGyDlv8X0CwnWBv3/xSnCefgxbsS7oRhdLbpyQxJsEyl1uKr6ogXmjTuimkDSexMDFccrayKT0f0MYBc+3vw+zpNIlkfzMgz0OViohX+nartiQxSGJ3+yNQg8zwovM0HGYxVKPwssWqxT4L3tx2uxCOwm1wXJPO1N8IUxBMMsA2afdLNRtPkHWbjFUqOzPtC896EZga64Fly9DGnwcfcnjO+o7JAL98AjCgX12CJlhjKYdinTIlnqHjsepK6Heh5sa1TijL0lqGY3xIPPK283vIMH9PKJU/YhWX9CctgaptWVkMAjtNxDRqkA0yvYgXQGVREQrW2Qsx3knTI+FQJbCYPVU3t7jhxnyWtFzuAB3itWumScoWf4rFiZIA83+W7zMeCr70qVXzF27fpIyoOZ+xL5z/xtZvEstHhjVVMaVVW9BLbdqf/GqY5LbbfR96NoPh+mP8Rjso=
